name = "docbuild"
reservoir = false
version = "0.1.0"
packagesDir = "../.lake/packages"

[[require]]
scope = "leanprover"
name = "«doc-gen4»"
rev = "386e1a1a67d9264fef16789c2beaeb7aaa8b88e1"

[[require]]
name = "Project"
path = "../programs/lean"
