import {
  Artifact,
  Diagnostic,
  ExportedFunction,
  FormalSpec,
  LoadedArtifact,
  SourceFile,
  Verification,
} from "./types.js";
import { codeBlock, escape } from "./html.js";
import { STYLE } from "./style.js";
import { LEAN_HLJS_REGISTER } from "./lean-hljs.js";

const HLJS_CDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.9.0/build";

function page(title: string, body: string, depthToRoot: number): string {
  const rel = "../".repeat(depthToRoot);
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escape(title)}</title>
<link rel="stylesheet" href="${HLJS_CDN}/styles/github.min.css" />
<link rel="stylesheet" href="${rel}style.css" />
</head>
<body>
<div class="container">
${body}
<footer class="site">Generated by <code>talos-report</code> from <code>verifier extract</code> artifacts.</footer>
</div>
<script src="${HLJS_CDN}/highlight.min.js"></script>
<script>${LEAN_HLJS_REGISTER}</script>
<script>hljs.highlightAll();</script>
</body>
</html>`;
}

function loc(file: string, span: { start: { line: number } }): string {
  return `${file}:${span.start.line}`;
}

function severityBadge(sev: Diagnostic["severity"]): string {
  const cls = sev === "error" ? "bad" : sev === "warn" ? "warn" : "info";
  return `<span class="badge ${cls}">${sev}</span>`;
}

function projectSlug(art: Artifact): string {
  return art.project.name ?? art.project.crate ?? "(unknown)";
}

function statusBadge(art: Artifact): string {
  const errs = art.diagnostics.filter((d) => d.severity === "error").length;
  const warns = art.diagnostics.filter((d) => d.severity === "warn").length;
  const proven = art.specs.filter((s) =>
    art.verifications.some((v) => v.proves === s.name),
  ).length;
  if (errs > 0) return `<span class="badge bad">${errs} error${errs === 1 ? "" : "s"}</span>`;
  if (art.specs.length > 0 && proven === art.specs.length)
    return `<span class="badge good">verified</span>`;
  if (art.specs.length > 0)
    return `<span class="badge warn">${proven}/${art.specs.length} proven</span>`;
  if (warns > 0) return `<span class="badge warn">${warns} warn${warns === 1 ? "" : "s"}</span>`;
  return `<span class="badge muted">no specs</span>`;
}

export function renderIndex(arts: LoadedArtifact[]): string {
  const totalSpecs = arts.reduce((n, a) => n + a.data.specs.length, 0);
  const totalVerifs = arts.reduce((n, a) => n + a.data.verifications.length, 0);
  const totalExports = arts.reduce((n, a) => n + a.data.exported.length, 0);
  const totalDiags = arts.reduce((n, a) => n + a.data.diagnostics.length, 0);

  const first = arts[0]?.data;
  const headerMeta = first
    ? `<div class="meta">
        repo @ <code>${escape(first.repo_commit.slice(0, 12))}</code>
        · rustc edition <code>${escape(first.toolchains.rustc ?? "?")}</code>
        · ${escape(first.toolchains.lean)}
        · extracted ${escape(first.extracted_at)}
       </div>`
    : "";

  const rows = arts
    .map((a) => {
      const slug = projectSlug(a.data);
      return `<tr>
        <td class="slug"><a href="projects/${escape(a.slug)}.html">${escape(slug)}</a></td>
        <td class="num">${a.data.exported.length}</td>
        <td class="num">${a.data.specs.length}</td>
        <td class="num">${a.data.verifications.length}</td>
        <td class="num">${a.data.diagnostics.length}</td>
        <td>${statusBadge(a.data)}</td>
      </tr>`;
    })
    .join("");

  const body = `
<header class="site">
  <h1>Talos · verification progress</h1>
  ${headerMeta}
</header>

<section class="summary-grid">
  <div class="stat"><div class="label">Projects</div><div class="value">${arts.length}</div></div>
  <div class="stat"><div class="label">Exported fns</div><div class="value">${totalExports}</div></div>
  <div class="stat"><div class="label">Formal specs</div><div class="value">${totalSpecs}</div></div>
  <div class="stat"><div class="label">Verifications</div><div class="value">${totalVerifs}</div></div>
  <div class="stat"><div class="label">Diagnostics</div><div class="value">${totalDiags}</div></div>
</section>

<h2>Projects</h2>
<table>
  <thead>
    <tr>
      <th>Project</th><th>Exports</th><th>Specs</th><th>Proofs</th><th>Diagnostics</th><th>Status</th>
    </tr>
  </thead>
  <tbody>${rows}</tbody>
</table>
`;
  return page("Talos verification progress", body, 0);
}

function renderExported(fns: ExportedFunction[]): string {
  if (fns.length === 0) return `<div class="empty">No <code>#[no_mangle] extern "C"</code> exports were discovered by the extractor.</div>`;
  return fns
    .map(
      (f) => `<div class="card">
        <div class="head">
          <span class="name">${escape(f.name)}</span>
          <span class="loc">${escape(loc(f.location.file, f.location.span))}</span>
        </div>
        ${f.docstring ? `<div class="docstring">${escape(f.docstring)}</div>` : ""}
        ${codeBlock(f.signature, "rust")}
      </div>`,
    )
    .join("");
}

function renderSpec(spec: FormalSpec, verifs: Verification[]): string {
  const matching = verifs.filter((v) => v.proves === spec.name);
  const status =
    matching.length > 0
      ? `<span class="badge good">${matching.length} proof${matching.length === 1 ? "" : "s"}</span>`
      : `<span class="badge warn">unproven</span>`;
  const refs = spec.refs.length
    ? `<h3>References</h3><ul class="refs">${spec.refs
        .map(
          (r) =>
            `<li><span class="badge ${r.resolved ? "good" : "muted"}">${escape(r.kind)}</span> ${escape(r.target)}</li>`,
        )
        .join("")}</ul>`
    : "";
  const informal = spec.informal
    ? `<h3>Informal spec</h3><div class="docstring">${escape(spec.informal)}</div>`
    : "";
  const proofs = matching.length
    ? `<h3>Proofs</h3><ul class="refs">${matching
        .map(
          (v) =>
            `<li><span class="badge good">proves</span> ${escape(v.name)} <span class="loc">(${escape(loc(v.location.file, v.location.span))})</span></li>`,
        )
        .join("")}</ul>`
    : "";

  return `<div class="card">
    <div class="head">
      <span class="name">${escape(spec.name)}</span>
      <span class="badges">${status}</span>
    </div>
    <div class="loc">${escape(loc(spec.location.file, spec.location.span))}</div>
    ${spec.docstring.prose ? `<div class="docstring">${escape(spec.docstring.prose)}</div>` : ""}
    ${informal}
    <h3>Statement</h3>
    ${codeBlock(spec.statement, "lean")}
    ${refs}
    ${proofs}
  </div>`;
}

function renderVerifications(art: Artifact): string {
  const orphaned = art.verifications.filter(
    (v) => !art.specs.some((s) => s.name === v.proves),
  );
  if (orphaned.length === 0) return "";
  return `<h2>Orphan verifications</h2>
  <div class="empty">Theorems whose <code>@[proves …]</code> target was not found among this project's specs.</div>
  ${orphaned
    .map(
      (v) => `<div class="card">
      <div class="head">
        <span class="name">${escape(v.name)}</span>
        <span class="loc">${escape(loc(v.location.file, v.location.span))}</span>
      </div>
      <div>proves: <code>${escape(v.proves)}</code> <span class="badge ${v.resolved ? "good" : "warn"}">${v.resolved ? "resolved" : "unresolved"}</span></div>
    </div>`,
    )
    .join("")}`;
}

function renderDiagnostics(diags: Diagnostic[]): string {
  if (diags.length === 0) return `<div class="empty">No diagnostics.</div>`;
  return diags
    .map(
      (d) => `<div class="card">
        <div class="head">
          <span class="name">${escape(d.kind)}</span>
          <span class="badges">${severityBadge(d.severity)}</span>
        </div>
        ${d.location ? `<div class="loc">${escape(loc(d.location.file, d.location.span))}</div>` : ""}
        <div>${escape(d.message)}</div>
      </div>`,
    )
    .join("");
}

function langKey(f: SourceFile): string {
  switch (f.language) {
    case "rust":
    case "lean":
    case "toml":
      return f.language;
    case "wat":
      return "lisp"; // closest match in highlight.js
    case "toolchain":
      return "plaintext";
    default:
      return "plaintext";
  }
}

function renderSource(files: SourceFile[]): string {
  if (files.length === 0) return `<div class="empty">No source files recorded.</div>`;
  // Skip empty bodies (e.g. binary .wasm) gracefully.
  return files
    .map((f) => {
      const body = f.body
        ? codeBlock(f.body, langKey(f))
        : `<div class="empty">(binary or empty file — body not captured)</div>`;
      return `<details>
        <summary><span>${escape(f.filepath)}</span><span class="lang">${escape(f.language)} · ${f.line_count} lines</span></summary>
        ${body}
      </details>`;
    })
    .join("");
}

export function renderProject(art: Artifact): string {
  const slug = projectSlug(art);
  const body = `
<div class="crumbs"><a href="../index.html">← all projects</a></div>
<header class="site">
  <h1>${escape(slug)}</h1>
  <div class="meta">
    rust: <code>${escape(art.project.rust)}</code>
    · lean: <code>${escape(art.project.lean)}</code>
    · repo @ <code>${escape(art.repo_commit.slice(0, 12))}</code>
    · ${escape(art.toolchains.lean)}
  </div>
  <div style="margin-top:8px">${statusBadge(art)}</div>
</header>

<section class="summary-grid">
  <div class="stat"><div class="label">Exports</div><div class="value">${art.exported.length}</div></div>
  <div class="stat"><div class="label">Specs</div><div class="value">${art.specs.length}</div></div>
  <div class="stat"><div class="label">Verifications</div><div class="value">${art.verifications.length}</div></div>
  <div class="stat"><div class="label">Diagnostics</div><div class="value">${art.diagnostics.length}</div></div>
</section>

<h2>Exported functions</h2>
${renderExported(art.exported)}

<h2>Program</h2>
${
  art.program
    ? `<div class="card">
        <div class="head">
          <span class="name">${escape(art.program.module)}</span>
          <span class="loc">${escape(loc(art.program.location.file, art.program.location.span))}</span>
        </div>
        ${codeBlock(art.program.body, "lean")}
      </div>`
    : `<div class="empty">No <code>Program</code> recorded.</div>`
}

<h2>Formal specs</h2>
${
  art.specs.length === 0
    ? `<div class="empty">No specs discovered. (See diagnostics for whether <code>@[spec_of]</code> attributes are present.)</div>`
    : art.specs.map((s) => renderSpec(s, art.verifications)).join("")
}

${renderVerifications(art)}

<h2>Diagnostics</h2>
${renderDiagnostics(art.diagnostics)}

<h2>Source files</h2>
${renderSource(art.code)}
`;
  return page(`${slug} · Talos`, body, 1);
}
