/-
  AUTO-GENERATED by `lake exe verifier check`.
  Do not edit by hand. Edit Spec.lean (sibling) for proofs.
  The sibling `module.wat` is the source of truth; the drift check at
  the bottom of this file errors at elaboration time if it has changed
  without a corresponding re-emit.
-/

import CodeLib

set_option maxRecDepth 1048576

namespace Programs.Simple.XorSum

open Wasm

/-- export: xor_sum -/
def func0 : Wasm.Program :=
  [
  .const (0 : UInt32),
  .localSet 2,
  .block 0 0 [
    .localGet 1,
    .eqz,
    .br_if 0,
    .loop 0 0 [
      .localGet 0,
      .load32 (0 : UInt32),
      .localGet 2,
      .xor,
      .localSet 2,
      .localGet 0,
      .const (4 : UInt32),
      .add,
      .localSet 0,
      .localGet 1,
      .const (4294967295 : UInt32),
      .add,
      .localSet 1,
      .localGet 1,
      .br_if 0
    ]
  ],
  .localGet 2
]

def «module» : Wasm.Module :=
{
  funcs := [
    { params := [.i32, .i32], locals := [.i32], body := func0, results := some [.i32] }
  ],
  exports := [
    { name := "xor_sum", funcIdx := 0 }
  ],
  memory := some { pagesMin := (16 : UInt32), pagesMax := none, data := [] },
  globals := [
    { type := .i32, init := .i32 (1048576 : UInt32) },
    { type := .i32, init := .i32 (1048576 : UInt32) },
    { type := .i32, init := .i32 (1048576 : UInt32) }
  ]
}

/-- Hash of the source `module.wat` captured when `verifier check` last ran. -/
private def expectedWatHash : UInt64 := 13997200556762420734

-- Compile-time drift check: errors if `module.wat` has changed without a corresponding re-emit.
#guard_msgs (drop info) in
#eval show IO Unit from do
  let path : System.FilePath := "Programs/Simple/XorSum/module.wat"
  unless ← path.pathExists do return
  let actual ← IO.FS.readFile path
  if actual.hash ≠ expectedWatHash then
    throw <| IO.userError
      s!"{path} has drifted from Program.lean; re-run `lake exe verifier check`."

end Programs.Simple.XorSum
