/-
  AUTO-GENERATED by `verifier emit`. Do not edit by hand.
-/

import CodeLib.Generated

set_option maxRecDepth 1048576

namespace Project.RustArray

open Wasm

-- WAT SHA-256: 284f7f451dffab688e497a0da3bb446cf92bd6dcc7f00ea03e342166cc773047

def func0 : Wasm.Program := watFunctionBody% "../rust/build/rust_array/program.wat" 0

def func0Def : Wasm.Function :=
  { params := [.i32, .i32], body := func0, results := [.i32], typeIdx := some 0 }

def func1 : Wasm.Program := watFunctionBody% "../rust/build/rust_array/program.wat" 1

def func1Def : Wasm.Function :=
  { params := [.i32, .i32], body := func1, results := [.i32], typeIdx := some 0 }

def func2 : Wasm.Program := watFunctionBody% "../rust/build/rust_array/program.wat" 2

def func2Def : Wasm.Function :=
  { params := [.i32, .i32], body := func2, results := [.i32], typeIdx := some 0 }

def func3 : Wasm.Program := watFunctionBody% "../rust/build/rust_array/program.wat" 3

def func3Def : Wasm.Function :=
  { params := [.i32], locals := [.i32, .i32, .i32, .i32, .i32], body := func3, typeIdx := some 1 }

def func4 : Wasm.Program := watFunctionBody% "../rust/build/rust_array/program.wat" 4

def func4Def : Wasm.Function :=
  { params := [.i32], body := func4, results := [.i32], typeIdx := some 2 }

def func5 : Wasm.Program := watFunctionBody% "../rust/build/rust_array/program.wat" 5

def func5Def : Wasm.Function :=
  { params := [.i32], body := func5, results := [.i32], typeIdx := some 2 }

def «module» : Wasm.Module :=
  { (watModuleMetadata% "../rust/build/rust_array/program.wat") with funcs := [func0Def, func1Def, func2Def, func3Def, func4Def, func5Def] }

-- Compile-time fidelity check: errors if WAT and generated Lean AST differ.
#guard_msgs (drop info) in
#eval Wasm.checkWatFidelity "../rust/build/rust_array/program.wat" «module»

end Project.RustArray
