/-
  AUTO-GENERATED by `verifier emit`. Do not edit by hand.
-/

import CodeLib.Generated

set_option maxRecDepth 1048576

namespace Project.TotalVariation

open Wasm

-- WAT SHA-256: 702f26328cae66ccbbdf2aceb06a52bbec5437b01257666e65c419981fed0c7b

def func0 : Wasm.Program := watFunctionBody% "../rust/build/total_variation/program.wat" 0

def func0Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [.i32], body := func0, results := [.i64], typeIdx := some 0 }

def func1 : Wasm.Program := watFunctionBody% "../rust/build/total_variation/program.wat" 1

def func1Def : Wasm.Function :=
  { params := [.i64, .i64, .i64], body := func1, results := [.i64], typeIdx := some 1 }

def «module» : Wasm.Module :=
  { (watModuleMetadata% "../rust/build/total_variation/program.wat") with funcs := [func0Def, func1Def] }

-- Compile-time fidelity check: errors if WAT and generated Lean AST differ.
#guard_msgs (drop info) in
#eval Wasm.checkWatFidelity "../rust/build/total_variation/program.wat" «module»

end Project.TotalVariation
