/-
  AUTO-GENERATED by `verifier emit`. Do not edit by hand.
-/

import CodeLib.Generated

set_option maxRecDepth 1048576

namespace Project.FloatRound

open Wasm

-- WAT SHA-256: e57d177cf65ad6cf2d50c5654e05237498c2c299cac152f3acf760e024c769e7

def func0 : Wasm.Program := watFunctionBody% "../rust/build/float_round/program.wat" 0

def func0Def : Wasm.Function :=
  { params := [.f32], locals := [.i32, .f32, .f32, .f32], body := func0, results := [.f32], typeIdx := some 0 }

def func1 : Wasm.Program := watFunctionBody% "../rust/build/float_round/program.wat" 1

def func1Def : Wasm.Function :=
  { params := [.f32], locals := [.i32], body := func1, results := [.f32], typeIdx := some 0 }

def func2 : Wasm.Program := watFunctionBody% "../rust/build/float_round/program.wat" 2

def func2Def : Wasm.Function :=
  { params := [.f32], locals := [.i32], body := func2, results := [.f32], typeIdx := some 0 }

def func3 : Wasm.Program := watFunctionBody% "../rust/build/float_round/program.wat" 3

def func3Def : Wasm.Function :=
  { params := [.f32], locals := [.i32], body := func3, results := [.f32], typeIdx := some 0 }

def func4 : Wasm.Program := watFunctionBody% "../rust/build/float_round/program.wat" 4

def func4Def : Wasm.Function :=
  { params := [.f32], body := func4, results := [.f32], typeIdx := some 0 }

def func5 : Wasm.Program := watFunctionBody% "../rust/build/float_round/program.wat" 5

def func5Def : Wasm.Function :=
  { params := [.f32], locals := [.i32], body := func5, results := [.f32], typeIdx := some 0 }

def func6 : Wasm.Program := watFunctionBody% "../rust/build/float_round/program.wat" 6

def func6Def : Wasm.Function :=
  { params := [.f32], locals := [.i32, .i32], body := func6, results := [.i32], typeIdx := some 1 }

def «module» : Wasm.Module :=
  { (watModuleMetadata% "../rust/build/float_round/program.wat") with funcs := [func0Def, func1Def, func2Def, func3Def, func4Def, func5Def, func6Def] }

-- Compile-time fidelity check: errors if WAT and generated Lean AST differ.
#guard_msgs (drop info) in
#eval Wasm.checkWatFidelity "../rust/build/float_round/program.wat" «module»

end Project.FloatRound
