/-
  AUTO-GENERATED by `verifier emit`. Do not edit by hand.
-/

import CodeLib.Generated

set_option maxRecDepth 1048576

namespace Project.NumInteger

open Wasm

-- WAT SHA-256: 0c28bedbcb07efae48d493dcf39d5fd2234372fb403b05007493c62128bdc4b9

def func0 : Wasm.Program := watFunctionBody% "../rust/build/num_integer/program.wat" 0

def func0Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [.i32, .i64], body := func0, results := [.i64], typeIdx := some 0 }

def func1 : Wasm.Program := watFunctionBody% "../rust/build/num_integer/program.wat" 1

def func1Def : Wasm.Function :=
  { params := [.i32, .i32], locals := [.i32, .i32, .i32, .i32, .i64, .i32, .i64, .i32], body := func1, results := [.i64], typeIdx := some 1 }

def func2 : Wasm.Program := watFunctionBody% "../rust/build/num_integer/program.wat" 2

def func2Def : Wasm.Function :=
  { params := [.i64, .i64], body := func2, results := [.i64], typeIdx := some 0 }

def «module» : Wasm.Module :=
  { (watModuleMetadata% "../rust/build/num_integer/program.wat") with funcs := [func0Def, func1Def, func2Def] }

-- Compile-time fidelity check: errors if WAT and generated Lean AST differ.
#guard_msgs (drop info) in
#eval Wasm.checkWatFidelity "../rust/build/num_integer/program.wat" «module»

end Project.NumInteger
