/-
  AUTO-GENERATED by `lake exe verifier check`.
  Do not edit by hand. Edit Spec.lean (sibling) for proofs.
  The sibling `module.wat` is the source of truth; the drift check at
  the bottom of this file errors at elaboration time if it has changed
  without a corresponding re-emit.
-/

import CodeLib

set_option maxRecDepth 1048576

namespace Programs.Crates.NumInteger

open Wasm

/-- export: gcd_u64 -/
def func0 : Wasm.Program :=
  [
  .localGet 1,
  .localGet 0,
  .orI64,
  .localSet 2,
  .block 0 0 [
    .localGet 0,
    .eqzI64,
    .br_if 0,
    .localGet 1,
    .eqzI64,
    .br_if 0,
    .localGet 2,
    .ctzI64,
    .localSet 3,
    .block 0 0 [
      .block 0 0 [
        .localGet 0,
        .localGet 0,
        .ctzI64,
        .shrUI64,
        .localSet 2,
        .localGet 2,
        .localGet 1,
        .localGet 1,
        .ctzI64,
        .shrUI64,
        .localSet 0,
        .localGet 0,
        .neI64,
        .br_if 0,
        .localGet 2,
        .localSet 0,
        .br 1
      ],
      .loop 0 0 [
        .block 0 0 [
          .block 0 0 [
            .localGet 2,
            .localGet 0,
            .gtUI64,
            .br_if 0,
            .localGet 0,
            .localGet 2,
            .subI64,
            .localSet 0,
            .localGet 0,
            .localGet 0,
            .ctzI64,
            .shrUI64,
            .localSet 0,
            .br 1
          ],
          .localGet 2,
          .localGet 0,
          .subI64,
          .localSet 2,
          .localGet 2,
          .localGet 2,
          .ctzI64,
          .shrUI64,
          .localSet 2
        ],
        .localGet 2,
        .localGet 0,
        .neI64,
        .br_if 0
      ]
    ],
    .localGet 0,
    .localGet 3,
    .shlI64,
    .localSet 2
  ],
  .localGet 2
]

def «module» : Wasm.Module :=
{
  funcs := [
    { params := [.i64, .i64], locals := [.i64, .i64], body := func0, results := some [.i64] }
  ],
  exports := [
    { name := "gcd_u64", funcIdx := 0 }
  ],
  memory := some { pagesMin := (16 : UInt32), pagesMax := none, data := [] },
  globals := [
    { type := .i32, init := .i32 (1048576 : UInt32) },
    { type := .i32, init := .i32 (1048576 : UInt32) },
    { type := .i32, init := .i32 (1048576 : UInt32) }
  ]
}

/-- Hash of the source `module.wat` captured when `verifier check` last ran. -/
private def expectedWatHash : UInt64 := 15244946472501003244

-- Compile-time drift check: errors if `module.wat` has changed without a corresponding re-emit.
#eval show IO Unit from do
  let path : System.FilePath := "Programs/Crates/NumInteger/module.wat"
  unless ← path.pathExists do return
  let actual ← IO.FS.readFile path
  if actual.hash ≠ expectedWatHash then
    throw <| IO.userError
      s!"{path} has drifted from Program.lean; re-run `lake exe verifier check`."

end Programs.Crates.NumInteger
