/-
  AUTO-GENERATED by `verifier emit`. Do not edit by hand.
-/

import CodeLib

set_option maxRecDepth 1048576

namespace Project.NumIntegerOpt3

open Wasm

/-- export: gcd_u64 -/
def func0 : Wasm.Program :=
  [
  .localGet 1,
  .localGet 0,
  .orI64,
  .localSet 2,
  .block 0 0 [
    .localGet 0,
    .eqzI64,
    .br_if 0,
    .localGet 1,
    .eqzI64,
    .br_if 0,
    .localGet 2,
    .ctzI64,
    .localSet 2,
    .block 0 0 [
      .localGet 0,
      .localGet 0,
      .ctzI64,
      .shrUI64,
      .localSet 0,
      .localGet 0,
      .localGet 1,
      .localGet 1,
      .ctzI64,
      .shrUI64,
      .localSet 1,
      .localGet 1,
      .eqI64,
      .br_if 0,
      .loop 0 0 [
        .block 0 0 [
          .localGet 0,
          .localGet 1,
          .gtUI64,
          .br_if 0,
          .localGet 0,
          .localGet 1,
          .localGet 0,
          .subI64,
          .localSet 1,
          .localGet 1,
          .localGet 1,
          .ctzI64,
          .shrUI64,
          .localSet 1,
          .localGet 1,
          .eqI64,
          .br_if 2,
          .br 1
        ],
        .localGet 0,
        .localGet 1,
        .subI64,
        .localSet 0,
        .localGet 0,
        .localGet 0,
        .ctzI64,
        .shrUI64,
        .localSet 0,
        .localGet 0,
        .localGet 1,
        .neI64,
        .br_if 0
      ],
      .localGet 1,
      .localSet 0
    ],
    .localGet 0,
    .localGet 2,
    .shlI64,
    .localSet 2
  ],
  .localGet 2
]

def func0Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [.i64], body := func0, results := [.i64] }

def «module» : Wasm.Module :=
{
  imports := [],
  funcs := [
    func0Def
  ],
  exports := [
    { name := "gcd_u64", funcIdx := 0 }
  ],
  memory := some { pagesMin := (16 : UInt32), pagesMax := none, data := [] },
  globals := [
    { init := .i32 (1048576 : UInt32) },
    { init := .i32 (1048576 : UInt32) },
    { init := .i32 (1048576 : UInt32) }
  ],
  types := [
    { params := [.i64, .i64], results := [.i64] }
  ],
  tables := [
    { min := 1, max := some 1, elemType := .funcref }
  ],
  elements := []
}

end Project.NumIntegerOpt3
