/-
  AUTO-GENERATED by `verifier emit`. Do not edit by hand.
-/

import CodeLib.Generated

set_option maxRecDepth 1048576

namespace Project.NumIntegerOpt3

open Wasm

-- WAT SHA-256: 0699c0b15e43ad867796e2b30ddd4a531604c8ca2e4818990f8915c6dcba3def

def func0 : Wasm.Program := watFunctionBody% "../rust/build/num_integer_opt3/program.wat" 0

def func0Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [.i64], body := func0, results := [.i64], typeIdx := some 0 }

def «module» : Wasm.Module :=
  { (watModuleMetadata% "../rust/build/num_integer_opt3/program.wat") with funcs := [func0Def] }

-- Compile-time fidelity check: errors if WAT and generated Lean AST differ.
#guard_msgs (drop info) in
#eval Wasm.checkWatFidelity "../rust/build/num_integer_opt3/program.wat" «module»

end Project.NumIntegerOpt3
