/-
  AUTO-GENERATED by `lake exe verifier check`.
  Do not edit by hand. Edit Spec.lean (sibling) for proofs.
  The sibling `module.wat` is the source of truth; the drift check at
  the bottom of this file errors at elaboration time if it has changed
  without a corresponding re-emit.
-/

import CodeLib

set_option maxRecDepth 1048576

namespace Programs.Simple.IsEven

open Wasm

/-- export: is_even -/
def func0 : Wasm.Program :=
  [
  .localGet 0,
  .const (1 : UInt32),
  .and,
  .eqz
]

def «module» : Wasm.Module :=
{
  funcs := [
    { params := [.i32], locals := [], body := func0 }
  ],
  exports := [
    { name := "is_even", funcIdx := 0 }
  ]
}

/-- Hash of the source `module.wat` captured when `verifier check` last ran. -/
private def expectedWatHash : UInt64 := 14167061999100621

-- Compile-time drift check: errors if `module.wat` has changed without a corresponding re-emit.
#eval show IO Unit from do
  let path : System.FilePath := "Programs/Simple/IsEven/module.wat"
  unless ← path.pathExists do return
  let actual ← IO.FS.readFile path
  if actual.hash ≠ expectedWatHash then
    throw <| IO.userError
      s!"{path} has drifted from Program.lean; re-run `lake exe verifier check`."

end Programs.Simple.IsEven
