/-
  AUTO-GENERATED by `lake exe verifier check`. Do not edit by hand.
-/

import CodeLib

set_option maxRecDepth 1048576

namespace Project.IsOdd

open Wasm

/-- export: is_odd -/
def func0 : Wasm.Program :=
  [
  .localGet 0,
  .const (1 : UInt32),
  .and
]

/-- export: is_even -/
def func1 : Wasm.Program :=
  [
  .localGet 0,
  .const (1 : UInt32),
  .and,
  .eqz
]

def «module» : Wasm.Module :=
{
  funcs := [
    { params := [.i32], locals := [], body := func0, results := some [.i32] },
    { params := [.i32], locals := [], body := func1, results := some [.i32] }
  ],
  exports := [
    { name := "is_odd", funcIdx := 0 },
    { name := "is_even", funcIdx := 1 }
  ],
  memory := some { pagesMin := (16 : UInt32), pagesMax := none, data := [] },
  globals := [
    { type := .i32, init := .i32 (1048576 : UInt32) },
    { type := .i32, init := .i32 (1048576 : UInt32) },
    { type := .i32, init := .i32 (1048576 : UInt32) }
  ]
}

end Project.IsOdd
