/-
  AUTO-GENERATED by `verifier emit`. Do not edit by hand.
-/

import CodeLib.Generated

set_option maxRecDepth 1048576

namespace Project.FloatReinterpret

open Wasm

-- WAT SHA-256: d45391341e5bee9b42b8271c06baf8a8b65d6c64d590f7490e8de9ca8c7a55ba

def func0 : Wasm.Program := watFunctionBody% "../rust/build/float_reinterpret/program.wat" 0

def func0Def : Wasm.Function :=
  { params := [.f32], body := func0, results := [.f32], typeIdx := some 0 }

def func1 : Wasm.Program := watFunctionBody% "../rust/build/float_reinterpret/program.wat" 1

def func1Def : Wasm.Function :=
  { params := [.f32], locals := [.i32], body := func1, results := [.f32], typeIdx := some 0 }

def func2 : Wasm.Program := watFunctionBody% "../rust/build/float_reinterpret/program.wat" 2

def func2Def : Wasm.Function :=
  { params := [.f32], body := func2, results := [.f32], typeIdx := some 0 }

def func3 : Wasm.Program := watFunctionBody% "../rust/build/float_reinterpret/program.wat" 3

def func3Def : Wasm.Function :=
  { params := [.f64], locals := [.i32], body := func3, results := [.f64], typeIdx := some 1 }

def func4 : Wasm.Program := watFunctionBody% "../rust/build/float_reinterpret/program.wat" 4

def func4Def : Wasm.Function :=
  { params := [.f32, .f32], body := func4, results := [.f32], typeIdx := some 2 }

def func5 : Wasm.Program := watFunctionBody% "../rust/build/float_reinterpret/program.wat" 5

def func5Def : Wasm.Function :=
  { params := [.f32], body := func5, results := [.i32], typeIdx := some 3 }

def func6 : Wasm.Program := watFunctionBody% "../rust/build/float_reinterpret/program.wat" 6

def func6Def : Wasm.Function :=
  { params := [.i32], body := func6, results := [.f32], typeIdx := some 4 }

def func7 : Wasm.Program := watFunctionBody% "../rust/build/float_reinterpret/program.wat" 7

def func7Def : Wasm.Function :=
  { params := [.f32, .f32], body := func7, results := [.f32], typeIdx := some 2 }

def func8 : Wasm.Program := watFunctionBody% "../rust/build/float_reinterpret/program.wat" 8

def func8Def : Wasm.Function :=
  { params := [.f32, .f32], locals := [.i32], body := func8, results := [.f32], typeIdx := some 2 }

def func9 : Wasm.Program := watFunctionBody% "../rust/build/float_reinterpret/program.wat" 9

def func9Def : Wasm.Function :=
  { params := [.f32], body := func9, results := [.f32], typeIdx := some 0 }

def func10 : Wasm.Program := watFunctionBody% "../rust/build/float_reinterpret/program.wat" 10

def func10Def : Wasm.Function :=
  { params := [.f32], locals := [.i32, .i32], body := func10, results := [.i32], typeIdx := some 3 }

def func11 : Wasm.Program := watFunctionBody% "../rust/build/float_reinterpret/program.wat" 11

def func11Def : Wasm.Function :=
  { params := [.f32, .f32], locals := [.i32, .i32], body := func11, results := [.i32], typeIdx := some 5 }

def «module» : Wasm.Module :=
  { (watModuleMetadata% "../rust/build/float_reinterpret/program.wat") with funcs := [func0Def, func1Def, func2Def, func3Def, func4Def, func5Def, func6Def, func7Def, func8Def, func9Def, func10Def, func11Def] }

-- Compile-time fidelity check: errors if WAT and generated Lean AST differ.
#guard_msgs (drop info) in
#eval Wasm.checkWatFidelity "../rust/build/float_reinterpret/program.wat" «module»

end Project.FloatReinterpret
