/-
  AUTO-GENERATED by `lake exe verifier check`.
  Do not edit by hand. Edit Spec.lean (sibling) for proofs.
  The sibling `module.wat` is the source of truth; the drift check at
  the bottom of this file errors at elaboration time if it has changed
  without a corresponding re-emit.
-/

import CodeLib

set_option maxRecDepth 1048576

namespace Programs.RustStd.Option

open Wasm

/-- export: filter_positive -/
def func0 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 (9223372036854775808 : UInt64),
  .localGet 0,
  .constI64 (0 : UInt64),
  .gtSI64,
  .select
]

/-- export: is_some -/
def func1 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 (9223372036854775808 : UInt64),
  .neI64
]

/-- export: map_add -/
def func2 : Wasm.Program :=
  [
  .constI64 (9223372036854775808 : UInt64),
  .localGet 1,
  .localGet 0,
  .addI64,
  .localGet 0,
  .constI64 (9223372036854775808 : UInt64),
  .eqI64,
  .select
]

/-- exports: or, unwrap_or -/
def func3 : Wasm.Program :=
  [
  .localGet 1,
  .localGet 0,
  .localGet 0,
  .constI64 (9223372036854775808 : UInt64),
  .eqI64,
  .select
]

/-- export: unwrap_or_default -/
def func4 : Wasm.Program :=
  [
  .constI64 (0 : UInt64),
  .localGet 0,
  .localGet 0,
  .constI64 (9223372036854775808 : UInt64),
  .eqI64,
  .select
]

/-- export: wrap -/
def func5 : Wasm.Program :=
  [
  .localGet 0
]

def «module» : Wasm.Module :=
{
  funcs := [
    { params := [.i64], locals := [], body := func0 },
    { params := [.i64], locals := [], body := func1 },
    { params := [.i64, .i64], locals := [], body := func2 },
    { params := [.i64, .i64], locals := [], body := func3 },
    { params := [.i64], locals := [], body := func4 },
    { params := [.i64], locals := [], body := func5 }
  ],
  exports := [
    { name := "filter_positive", funcIdx := 0 },
    { name := "is_some", funcIdx := 1 },
    { name := "map_add", funcIdx := 2 },
    { name := "or", funcIdx := 3 },
    { name := "unwrap_or_default", funcIdx := 4 },
    { name := "wrap", funcIdx := 5 },
    { name := "unwrap_or", funcIdx := 3 }
  ]
}

/-- Hash of the source `module.wat` captured when `verifier check` last ran. -/
private def expectedWatHash : UInt64 := 6850677042129948027

-- Compile-time drift check: errors if `module.wat` has changed without a corresponding re-emit.
#eval show IO Unit from do
  let path : System.FilePath := "Programs/RustStd/Option/module.wat"
  unless ← path.pathExists do return
  let actual ← IO.FS.readFile path
  if actual.hash ≠ expectedWatHash then
    throw <| IO.userError
      s!"{path} has drifted from Program.lean; re-run `lake exe verifier check`."

end Programs.RustStd.Option
