import Verifier.Config

/-!
# Phase 2 — Lean-side symbol extraction

For each lean project being checked, the verifier writes a generated
`_VerifierExtract.lean` at the project root and registers an exe target
for it (idempotently). The exe imports the project's library root,
walks `Environment.constants`, and emits JSON on stdout for the
requested namespace.
-/

namespace Verifier.Extract

open System (FilePath)

/-- The generated `_VerifierExtract.lean` source. `LIB` is the project's
top-level library module name (substituted at write time). -/
def templateLines (lib : String) : List String := [
  "-- AUTO-GENERATED by `lake exe verifier check`. Do not edit by hand.",
  s!"import {lib}",
  "import Lean",
  "",
  "open Lean",
  "",
  "namespace «_VerifierExtract»",
  "",
  "private partial def stripForalls : Expr → Expr",
  "  | .forallE _ _ body _ => stripForalls body",
  "  | e => e",
  "",
  "private def hex4 (n : Nat) : String :=",
  "  let h := Nat.toDigits 16 n",
  "  let s := String.mk h",
  "  let pad := String.mk (List.replicate (4 - s.length) '0')",
  "  pad ++ s",
  "",
  "private def escapeJsonString (s : String) : String :=",
  "  s.foldl (init := \"\") fun acc c =>",
  "    match c with",
  "    | '\"'  => acc ++ \"\\\\\\\"\"",
  "    | '\\\\' => acc ++ \"\\\\\\\\\"",
  "    | '\\n' => acc ++ \"\\\\n\"",
  "    | '\\r' => acc ++ \"\\\\r\"",
  "    | '\\t' => acc ++ \"\\\\t\"",
  "    | c    =>",
  "      if c.toNat < 0x20 then acc ++ \"\\\\u\" ++ hex4 c.toNat",
  "      else acc.push c",
  "",
  "private def jstr (s : String) : String := \"\\\"\" ++ escapeJsonString s ++ \"\\\"\"",
  "",
  "private def jopt : Option String → String",
  "  | some s => jstr s",
  "  | none   => \"null\"",
  "",
  "private def joptName : Option Name → String",
  "  | some n => jstr n.toString",
  "  | none   => \"null\"",
  "",
  "private def emitSpec (name : Name) (stmt : String) (doc : Option String) : String :=",
  "  \"{\\\"name\\\":\" ++ jstr name.toString",
  "    ++ \",\\\"statement\\\":\" ++ jstr stmt",
  "    ++ \",\\\"doc\\\":\" ++ jopt doc",
  "    ++ \"}\"",
  "",
  "private def emitProof (name : Name) (proves : Option Name)",
  "    (stmt : String) (doc : Option String) : String :=",
  "  \"{\\\"name\\\":\" ++ jstr name.toString",
  "    ++ \",\\\"proves\\\":\" ++ joptName proves",
  "    ++ \",\\\"type\\\":\" ++ jstr stmt",
  "    ++ \",\\\"doc\\\":\" ++ jopt doc",
  "    ++ \"}\"",
  "",
  "unsafe def runOnNamespace (env : Environment) (ns : Name) : IO Unit := do",
  "  let mut specs : Array String := #[]",
  "  let mut proofs : Array String := #[]",
  "  let mut specNames : NameSet := {}",
  "  for (name, ci) in env.constants.toList do",
  "    if !ns.isPrefixOf name then continue",
  "    match ci with",
  "    | .defnInfo i =>",
  "      if i.type.isProp then",
  "        let doc ← Lean.findDocString? env name",
  "        specs := specs.push (emitSpec name (toString i.type) doc)",
  "        specNames := specNames.insert name",
  "    | _ => pure ()",
  "  for (name, ci) in env.constants.toList do",
  "    if !ns.isPrefixOf name then continue",
  "    match ci with",
  "    | .thmInfo i =>",
  "      let head := (stripForalls i.type).getAppFn",
  "      let proves := match head with",
  "        | .const n _ => if specNames.contains n then some n else none",
  "        | _          => none",
  "      let doc ← Lean.findDocString? env name",
  "      proofs := proofs.push (emitProof name proves (toString i.type) doc)",
  "    | _ => pure ()",
  "  let specJson  := \"[\" ++ String.intercalate \",\" specs.toList ++ \"]\"",
  "  let proofJson := \"[\" ++ String.intercalate \",\" proofs.toList ++ \"]\"",
  "  IO.println (\"{\\\"namespace\\\":\" ++ jstr ns.toString",
  "    ++ \",\\\"specs\\\":\" ++ specJson",
  "    ++ \",\\\"proofs\\\":\" ++ proofJson",
  "    ++ \"}\")",
  "",
  "end «_VerifierExtract»",
  "",
  "unsafe def main (args : List String) : IO UInt32 := do",
  "  match args with",
  "  | [nsStr] =>",
  "    let env ← Lean.importModules #[{ module := `" ++ lib ++ " }] {} (loadExts := true)",
  "    «_VerifierExtract».runOnNamespace env nsStr.toName",
  "    return 0",
  "  | _ =>",
  "    IO.eprintln \"usage: _verifier_extract <namespace>\"",
  "    return 1",
  ""
]

/-- Render the template with the given library name. -/
def renderTemplate (libName : String) : String :=
  String.intercalate "\n" (templateLines libName)

/-- Lakefile stanza that registers the extractor exe. -/
def lakefileStanza : String :=
  String.intercalate "\n" [
    "",
    "[[lean_exe]]",
    "name = \"_verifier_extract\"",
    "root = \"_VerifierExtract\"",
    ""
  ]

/-- Ensure `_VerifierExtract.lean` exists at the project root and the
lakefile has the exe target. Idempotent. -/
def installExtractor (leanDir : FilePath) (libName : String) : IO Unit := do
  let leanFile := leanDir / "_VerifierExtract.lean"
  let desired := renderTemplate libName
  let needsWrite ← do
    if ← System.FilePath.pathExists leanFile then
      let cur ← IO.FS.readFile leanFile
      pure (cur != desired)
    else pure true
  if needsWrite then
    IO.FS.writeFile leanFile desired
  let lakefile := leanDir / "lakefile.toml"
  let content ← IO.FS.readFile lakefile
  let hasStanza := content.splitOn "\n" |>.any
    (fun line => line.trimAscii.startsWith "name = \"_verifier_extract\"")
  unless hasStanza do
    IO.FS.writeFile lakefile (content ++ lakefileStanza)

end Verifier.Extract
